### ISSUE TITLE
Add support for a "feature image".

### ISSUE THREAD

**Issue by michael-conrad** [Worble/Zulma#8]
Add support for a "feature image".

```
[extras]
feature_image="some file or function image resize return"
```

To show per post and in posts list.

**Comment by Worble** [comment]
Could you be a little more specific? You can already set an image on the front page by adding a little css as I show in [the readme](https://github.com/Worble/Zulma#title):

```css
.index .hero-body {
    background-image: url(https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Plum_trees_Kitano_Tenmangu.jpg/1200px-Plum_trees_Kitano_Tenmangu.jpg);
}
```

Admittedly this is a little awkward, and could be a config option instead, although playing with the css gives you a lot more options for getting the size and positioning right with it.

Per post, do you mean something like this?
![Capture](https://user-images.githubusercontent.com/23124945/77236903-c9166a80-6bba-11ea-8575-17a54fc32c7a.PNG)

This can be achieved with a little markdown in the post:
```
+++
title = "What is Gutenberg"
date = 2017-09-20
+++

![](https://picsum.photos/800/300)
```

That will place an image right at the top of the post, although it won't be center aligned. Again this can be fixed with a little css:

```css
.article-body img {
  display: block;
  margin: auto
}
```

I hope this helps.

**Comment by michael-conrad** [comment]
I altered the templates with an initial attempt. See repo
CherokeeLanguage/CherokeeLessons.com.

Live site is at https://cherokeelessons.com

The featured image is used in both the pagination and individual post views.

I'm sure something more responsive and CSS correct could be accomplished by
someone more knowledgeable than me.

**Comment by Worble** [comment]
Ah I see. I think that looks alright to me. Like I say, you don't need to edit the template directly, you can just add an image to the top of the markdown (like shown above) and then style it appropriately with some css, so like you've added yourself:

```css
.article-body img {
  float: left;
  margin-right: 2rem;
}
```

One thing that I should probably add to the readme is how to actualy add your own css files in. You can do so by creating your own `index.html` in the `templates` folder. You can then add `extends "zulma/templates/index.html"` and use the block `extra_head` to add your own links to your own css files. For example:

```html
{% extends "zulma/templates/index.html" %}
{% block extra_head %}
  <link rel="stylesheet" href="{{ get_url(path="mystylesheet.css", trailing_slash=false) }}" />
{% endblock extra_head %}
```

**Comment by michael-conrad** [comment]
The embed as markdown doesn't deal with needing to different layouts for
the pix. Section vs page.

**Comment by betoissues** [comment]
This is something I've done on my site (https://www.betoissues.com/2019/04/conflicto-intereses/), although overriding the layout by adding some extras keys to the posts:
```toml
[extra]
featured_image = '/img/2019/04/featured_conflicto_de_intereses.jpg'
featured_credit = "Lukáš Rychvalský"
featured_link = 'https://stocksnap.io/photo/IC2UDAUNFF'
```
Then in templates, use these to populate, taking into account existence of the keys. Taking it further, got these images to display in metatags for sharing in social media.
